### ISSUE TITLE
BE Ajax 500 Error

### ISSUE THREAD

**Issue by prentice87** [mblaschke/TYPO3-metaseo#129]
When inside the MetaSEO Module and trying to get a List, Typo3 7.4.0 throws this: 

    No backend function registered for ajaxID "tx_metaseo_backend_ajax::page".

Is there a solution? I want to go live with my site asap and need MetaSeo urgently.

**Comment by thomaszbz** [comment]
Please send us following information for easier bug hunting:

    MetaSEO version
    TYPO3 version
    PHP version
    Operating System

For 7.x please make sure that you use the latest develop version. This is still an unstable version and not intended for production use. You can download it here: https://api.github.com/repos/mblaschke/TYPO3-metaseo/zipball/develop (don't care about version info, it should be a pre-2.0.0).

If it still does not work I guess it's because they removed ExtJS in the 7.4 release which was published some days ago #114 . If that's the case please let us know.

**Comment by prentice87** [comment]
MetaSEO is the 2.0.0 develop, it was the first thing i tried. PHP 5.6.11, Ubuntu 14.04.2 LTS.
The problem is still occurring. Even though i can only see it on the Firebug windows. It just doesn't load the list. The answere remains: <t3err>No backend function registered for ajaxID &quot;tx_metaseo_backend_ajax::page&quot;.</t3err>

**Comment by thomaszbz** [comment]
Ok, then we need to investigate on this. Should be #114 unless it is something different.

If you can provide further information on your investigation please let us know.

**Comment by prentice87** [comment]
I'm sorry i'm really not that deeply into the Extension development of Typo3. Where should i look, or what could i do?

**Comment by thomaszbz** [comment]
For instance, we should know if this is a PHP error or a Javascript error. Plus, we should know if ExtJS has been removed in HTML (Firefox: Login to Backend/Press F12/Network Analysis/Refresh, click SEO/Metatags in the left pane. Then you look for the requests which are for MetaSEO (visible in URL). We should know if ExtJS is provided in the HTML or not.

For older Versions, this is <script src="../typo3temp/compressor/ext-base-....js.gzip" type="text/javascript"></script> or similar ("ext-base-" is relevant). In TYPO3 CMS 6.2 it contains a comment "This file is part of Ext JS 3.4" which is basically what we need to render the backend GUI.

An interim fix might be to add ExtJS 3.4 in HTML if it is "missing" in Typo3 7.4. This would be an intentional breaking change in TYPO3 7.4, not a bug in TYPO3.

**Comment by prentice87** [comment]
Okay i found "/typo3temp/compressor/ext-base-df8407683179e9aa0f89af03c3bc9142.js" Which states "This file is part of Ext JS 3.4" when inside the MetaSEO module and selecting the Home site e.g.

**Comment by thomaszbz** [comment]
Please send me the URL in which you found the .js script.

Could be that this is not about #114 which would be lucky.

**Comment by prentice87** [comment]
http://www.charter-connection.de/typo3temp/compressor/ext-base-df8407683179e9aa0f89af03c3bc9142.js

Also i tried PHP 5.5.27 and it did not change anything.

**Comment by thomaszbz** [comment]
Here's the breaking change documentation about removed ExtJS (forge-68001):

https://wiki.typo3.org/TYPO3.CMS/Releases/7.4/Breaking#Breaking:_.2368001_-_Removed_ExtJS_Core_and_ExtJS_Adapters

Affected Installations

    Instances that use ExtCore in the TYPO3 Frontend
    Extensions that use <f:be.container> with an ExtJS Adapter
    Extensions that use the PageRenderer object directly to load custom ExtJS or ExtCore.

I guess, we're affected by this.

**Comment by prentice87** [comment]
Okay, so there is nothing i can do about it right now?

**Comment by thomaszbz** [comment]
Sorry, we're always some time behind newly released production versions of TYPO3. They broke it, it's not a TYPO3-bug and we need to fix it.

Not sure if this an option for you, but users tell us that 7.2 and maybe 7.3 should work.

**Comment by prentice87** [comment]
I will try and migrate back to 7.3.1, maybe that will work :)

**Comment by thomaszbz** [comment]
I'm still wondering about the error message and that you tell that there's still ExtJS in the HTML.

This is a similar error from another extension: https://forge.typo3.org/issues/40214
They replaced namespaces:

    \TYPO3\CMS\Backend\Utility\BackendUtility::setUpdateSignal('TYPO3\\CMS\\Opendocs\\Controller\\OpendocsController::updateNumber', count($this->docHandler));

with

    \TYPO3\CMS\Backend\Utility\BackendUtility::setUpdateSignal('OpendocsController::updateNumber', count($this->docHandler));

**Comment by prentice87** [comment]
Tell me where to replace it and i'll be happy to try and give feedback :)

**Comment by thomaszbz** [comment]
Could also be that we need to go for PSR-7 soon via #113

**Comment by prentice87** [comment]
If i can help in any way, please let me know. My copy of Patrick Lobachers book on Extabse extensions will arrive today...so knowledge wise i won't be much help until a few months from now (i hope) but if you need me to try anything.

**Comment by thomaszbz** [comment]
The names of the hooks have been renamed to be camel-case: 2846737235eeddd2bebd4e133560b7151065eead

Wondering that tx_metaseo_backend_ajax still is not as of 19e2754a269c8607ce0ab0a3f8b80c85dc23e7eb

**Comment by thomaszbz** [comment]
I can reproduce the status code 500 for Ajax call

Request:

> POST /typo3/ajax.php?ajaxID=tx_metaseo_backend_ajax%3A%3Apage&cmd=getList HTTP/1.1
> X-Requested-With: XMLHttpRequest
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/44.0.2403.89 Chrome/44.0.2403.89 Safari/537.36

Query string parameters

> source: ajaxID=tx_metaseo_backend_ajax%3A%3Apage&cmd=getList
> parsed: ajaxID:tx_metaseo_backend_ajax::page
>              cmd:getList

**Comment by thomaszbz** [comment]
We should make use of the [ExtensionManagementUtility](https://docs.typo3.org/typo3cms/CoreApiReference/JavaScript/Ajax/Backend/Index.html), introduced in TYPO3 6.2:

> Since TYPO3 CMS 6.2, the registration is done via an API, which provides CSRF protection on the AJAX call and an automatic registration of the AJAX call URL (in typo3conf/opendocs/ext_tables.php).

**Comment by thomaszbz** [comment]
The patch also contains a refactoring for (not) encoding Ajax URLs multiple times. Plus, as we now have CSRF protection, it's also a new feature.

The bug seems to be fixed now in 7.5.0-dev (and earlier versions of TYPO3).

@prentice87 Do you want to test the patch? At least the backend should work much better with 7.5.0-dev now. I did not test the rest of it. And I also did not test other versions yet, but there should also be another bug fixed for older versions in this branch. The patch is not yet merged in develop branch, you need to checkout my branch or download the zip (google for 'GitHub zip route').

**Comment by thomaszbz** [comment]
@prentice87 Update: it's merged in develop. I would be happy if you could give it a try and tell us if TYPO3 CMS 7.4.0 is running smoothly.
