### ISSUE TITLE
SitemapIndex URLs should support typolink config via TypoScript 

### ISSUE THREAD

**Issue by PeaceSfiSh** [mblaschke/TYPO3-metaseo#16]
With an instance running in a subdirectory (e.g. www.domain.com/subdir/) and the subdir configured in 
- sys_Domain (www.domain.com/subdir) and in
- config.absRefPrefix (/subdir) 

the subdir part occurs twice in the Sitemap URL. _e.g. typo3.vagrant.dev/www/www/index.php?id=1&type=8411..._

The link should be generated with typolink, see #15

**Comment by mblaschke** [comment]
Will be in future versions, sorry.

**Comment by thomaszbz** [comment]
@PeaceSfiSh As far as I can see in your commits, there are other changes that might make sense but don't deal with this issue #16. For the moment I'm not sure which has been bugfixing/coding style/cosmetics/feature requests/obsolete changes

Could you please open new issues for some of them and cherry-pick them against current develop branch. Would be nice to have one branch/PR per issue, then the change can be classified, discussed and possibly merged in ~2.0.0.

I'd be especially interested in critical bug fixes in current develop branch if there are any (besides of #16).

**Comment by PeaceSfiSh** [comment]
After struggling with Git I've updated my repo with the latest commits. I didn't see changes to some files since April, my fault. I'll put all possible Pull Requests into a separate branch from now on.

Markus already cherry-picked the important changes from the huge Pull Request.

Thanks for your feedback.

**Comment by thomaszbz** [comment]
I fixed an issue for `config.absRefPrefix` recently: #190. We considered `config.absRefPrefix` for a long time, #190 is just for the root page not getting indexed in that case. At least for `config.absRefPrefix` I can say that it works in 2.0.x and also indexes the root page in 2.0.2+. Just that I did not test with `sys_Domain` and  `config.absRefPrefix` _combined_.

> Markus already cherry-picked the important changes from the huge Pull Request.

As long as the relevant patches provided by @PeaceSfiSh were merged, I guess this issue is now fixed as of ~2.0.0.
