### ISSUE TITLE
compatibility 7.4 

### ISSUE THREAD

**Issue by cryadm** [mblaschke/TYPO3-metaseo#171]
Like to use metaseo in 7.4 

are there any plans to update and timeline available?

regards
cryadm

**Comment by mblaschke** [comment]
Branch `develop` should be compatible, we're plaing an update soon. Sorry for the delay but we used the time to refactore the extension.

**Comment by thomaszbz** [comment]
@cryadm
* MetaSEO's backend should be compatible with latest TYPO3 master (7.5.0-dev), including v7.4. I was testing a lot against 7.50 in recent days.
* MetaSEO's indexing functionality has not yet undergone a wide range of tests, but for the moment there's no relevant bugs I am aware of for the moment. Which is why it's likely that it already works with 7.4 and 7.5.0-dev.
* We encourage users to test against 7.4 and 7.5.0-dev. We already tested a lot and fixed a lot of compatibility issues. This is all done. If you still need compatibility fixes against 7.4 or 7.5.0, please let us know.
* Keep in mind that ``develop`` is not intended for production use. We might break it from time to time. 5e45ffc6e2 should be ok, at least for testing purposes.

**Comment by mischka** [comment]
@thomaszbz can you than update the ext_emconf.php in the deveop branch maby to 7.99.99?

**Comment by thomaszbz** [comment]
@mischka I can't look into the future which is why I don't know yet which breaking changes we are faced with when 7.5.0 and 7 LTS are released.

But I'll ask our release team (@mblaschke) if we can go for 7.4.0 in the develop branch.
