### ISSUE TITLE
Documentation on FAQ (Sitemap)

### ISSUE THREAD

**Issue by PanadeEdu** [mblaschke/TYPO3-metaseo#185]
The FAQ to the Topic Sitemaps states at one point: 

Problem:
The sitemap is empy.
Solution:
Check if you created the “tx_metaseo_sitemap_pages” database-table! We're using InnoDB as MySQL-Engine so you have to make sure that you have InnoDB-Support in your Hosting-Account (if not you should switch your hoster, InnoDB is a Standard-Feature in MySQL). As with 2.0.1 there is an error-message if the table doesn't exist.

This is not true, there is not table "tx_metaseo_sitemap_pages" therefore it is missleading to look for it.

**Comment by thomaszbz** [comment]
Thanks for pointing this out. Indeed, there is no such table with name ``tx_metaseo_sitemap_pages``.

**Comment by thomaszbz** [comment]
I'm closing this issue now.

* It's fixed in pre-2.0.0 develop branch (which is not live yet)
* I think this is not critical enough for a backport to 1.0.x (which will anyways be obsolete as soon as we release 2.0.0). Plus, we fixed so many issues in the FAQ section that it would mean a lot of duplicate work to backport parts of that.
