### ISSUE TITLE
Indexed Sitemap 

### ISSUE THREAD

**Issue by dieKnolle** [mblaschke/TYPO3-metaseo#186]
Hello,
i have a system where i was running tq_seo for an indexed sitemap. Everything worked fine. Now i 
changed to metaseo because of future compatibility. The table was created but it keeps being empty and so the sitemap.
I tried the version from the extension-manager 1.0.8 and the developer version 2.0 from github.
Typo 6.2.1
Any idea whats wrong?

**Comment by thomaszbz** [comment]
Thanks for reporting this.

Please make sure that you have

* cleared all caches (all three buttons if you can see them)
* clicked around in the frontend. The indexed sitemap is supposed to enlarge with visited pages and its subpages / child pages.
* Maybe uninstall metaseo, clear caches (also using the clear-cache button in the install tool), and install it again. I have tweaked around with caches and sometimes this helps.

TYPO3 CMS 6.2.1 is outdated. Current version is 6.2.16. Maybe some bugs have been fixed in the meantime, especially in terms of caching (which metaseo relies on).

Which PHP version are you using?
Can you see some interesting entries in your logs (TYPO3 and Apache)? Maybe with debug mode enabled?

Please tell us if you get the problem solved with one of these hints and which measurement was helping in the end (to help us help other users).

**Comment by dieKnolle** [comment]
Hello,
I performed following actions:
   - cleared all caches 
   - clicked around (in another browser)
   - un / installed and cleared several caches.
my PHP version is 5.6.16-2. 
The table is still empty.

**Comment by thomaszbz** [comment]
There's similar issues which have been resolved. Could you please go through #55 ? It contains a list of steps to mitigate the issue.

#62 is also similar.

It could still be a caching issue or maybe configuration. Please try the steps again now that you use 5.2.16. I guess one of the steps will help.

**Comment by dieKnolle** [comment]
So far nothing new. But i just noticed that in the typo backend in your control center is no website domain entry. Did i forget something? Or how do you set the domain of the website?

**Comment by thomaszbz** [comment]
Please try

* In the backend
* Left side: go to SEO/Control Center
* => You must see at least one entry with your root page. (That is the page you have configured as "root page" via Typo3's page properties. Did you configure a root page in the page properties?

* IF you see an item in the Control Center (a root page), what happens if you click on the item's "Sitemap/open" ?

Which data do you see in SEO/Sitemap? Is it right or wrong or empty?

Please check logs afterwards, maybe you hit a reportable bug when you are clicking around. However, this should not happen with the current develop branch.

**Comment by dieKnolle** [comment]
Hello again
in the SEO/Control Center i see my configured root page home.
When i click to open the sidemap its empty. Just the sitemapindex tag but no pages.
When i install tq_seo it works like a charm.
I installed and updated with the migration tool. But the metaseo sitemap table is still empty.
The logs don't show nothing interesting so far.
Right now i will use tq_seo. I keep you informed.

**Comment by mblaschke** [comment]
Please update to latest `develop` revision and set either or both `plugin.metaseo.sitemap.index.allowNoStaticCachable` or `plugin.metaseo.sitemap.index.allowNoCache` to 1 (TS constants)

**Comment by thomaszbz** [comment]
Closing this, due to code fix and missing feedback. We still have #271 open for the question what we do in general, without the workaround (via 2c064fe) applied.
