### ISSUE TITLE
Page title can't be editable via "SEO - MetaTags" module

### ISSUE THREAD

**Issue by itribe** [mblaschke/TYPO3-metaseo#261]
When I logged like a editor and used "SEO - MetaTags" I can't edit a page title:
https://monosnap.com/file/8rEVoy9IADFzmtk17eNYYvCcDUL3qC
But I can edit the page title via default page editing: https://monosnap.com/file/XPpb8lJu9ZtteL3El7Q74qnkCWuSuh

Permissions for this field were granted.
All other fields work fine.

If I use admin account all fine.

TYPO3 7.6.10
metaseo 2.0.0

**Comment by danilovq** [comment]
The reason is that "title" field is not excluded field for pages and pages_language_overlay tables. The checking `$this->getBackendUserAuthentication()->check('non_exclude_fields', 'pages:' . $fieldName)` in [AbstractPageSeoController.php](TYPO3-metaseo/Classes/Controller/Ajax/AbstractPageSeoController.php) returns false for title field always.
@thomaszbz I can provide a pull request, if you will advice what is better solution for fixing it. Is it better to have checking for TCA excluded fields? Or checkings for modifying field permissions could be disabled completely if `$fieldName` equals "title".

**Comment by thomaszbz** [comment]
Steps to reproduce against metaseo 2.0.1-dev 2955b3b2bd75e38561a5124b79a20780f662c2c5, TYPO3 7.6.11-dev:

- configure non-admin user with write access to page properties, switch to that user
- click "SEO/Metatags" in left sidebar
- click page to edit
- click "Page Title" in dropdown
- click item in "Page" column to edit the page title
- edit title and click "save" button

As admin user: Works as expected: changes are saved, no error message occurs

As a non-admin user: Can edit page title in TYPO3 page properties, but not in metaseo.

Result: User has access permissions in TYPO3 page properties but they don't apply in metaseo

Expected result: Access permissions in TYPO3 page properties should also apply in metaseo

Therefore, this is indeed a bug, and I could reproduce it.

**Comment by thomaszbz** [comment]
>  Is it better to have checking for TCA excluded fields? Or checkings for modifying field permissions could be disabled completely if `$fieldName` equals `"title"`.

Checking just by `$fieldName` equals `"title"` would not be valid because we still need to check if the user has access to the data object. We need to go through the infrastructure TYPO3 provides. That implies that we need to check access permissions in the same manner as TYPO3 usually does it.

I'd be happy to merge your PR. I'll assign you this issue as long as you are working on it. Please let me know if something changes.
