### ISSUE TITLE
Missing arguments after signal slot dispatching

### ISSUE THREAD

**Issue by danilovq** [mblaschke/TYPO3-metaseo#264]
Signal slot dispatcher returns passed arguments as array and arguments which were passed as references are missing after dispatching.

TYPO3 7.6.10
metaseo 2.0.0

**Comment by danilovq** [comment]
I prepared the [fix](https://github.com/danilovq/TYPO3-metaseo/commit/1a9e756656ea569dcbfa9e0ab8cad94bc8c96ffd)

**Comment by thomaszbz** [comment]
Thanks for the fix. I fully agree, that looked strange. I'm just wondering why this issue was not discovered earlier. Either you fixed a lot of bugs or we don't do much with the returned `$args`. I'll have to investigate which effect the fix actually has, besides the intended ones. At least, it might change some behaviour.

For the record:

    public static function callHookAndSignal($class, $name, $obj, &$args = null)

is supposed to return `&$args` by reference, but this variable only changes for the first call...

    Typo3GeneralUtility::callUserFunction($_funcRef, $args, $obj);

https://github.com/mblaschke/TYPO3-metaseo/blob/develop/Classes/Utility/GeneralUtility.php#L380

which is by reference according to the function's signature:

    public static function callUserFunction($funcName, &$params, &$ref, $checkPrefix = '', $errorMode = 0)


But it does not change for the second call...

    $signalSlotDispatcher->dispatch($class, $name, array($args, $obj));

https://github.com/mblaschke/TYPO3-metaseo/blob/develop/Classes/Utility/GeneralUtility.php#L395

which is _not_ by reference according to the function's signature:

    public function dispatch($signalClassName, $signalName, array $signalArguments = array())

**Comment by thomaszbz** [comment]
The line in question got introduced with 6f17c54f20819917a9c2cd3f137e3f70b3195f5d.

Before that, there was no signalling at all and also $args was not touched. Basically that means that the input also got put out. I'll have to investigate if this is wanted behaviour or not.
