### ISSUE TITLE
sitemap - PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted

### ISSUE THREAD

**Issue by ducatisti-bln** [mblaschke/TYPO3-metaseo#270]
Hi,

we have a problem with creating the sitemap.xml or sitemap.txt. 
The table tx_metaseo_sitemap has around 1.8 Million entries. That's correct. 
But
`$list = SitemapUtility::getList($this->rootPid, $sysLanguageId);`
in Metaseo\Metaseo\Sitemap\Generator\AbstractGenerator __construct() dont can handle this.

TYPO3 6.2.23
MetaSEO 2.0.0

We set $TYPO3_CONF_VARS['SYS']['setMemoryLimit'] to  8124M. But this is absolutely not a solution

**Comment by thomaszbz** [comment]
For instance, 1.8 million entries in table tx_metaseo_sitemap sounds to me like you might want to  clean-up everything first. Otherwise, please confirm that you really want to transmit 1.8 million entries to a search engine.

It's not that metaseo is intentionally limited in that respect, rather the contrary. However, we have not been faced with 1.8 million entries right now (to my knowledge, at least).

For the clean-up, please make sure that you have

- updated to TYPO3 CMS 6.2.27 at least AND
- that you use `$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] = true;` which got introduced together with 6.2.27 to mitigate a DOS attack (see #268 for details!) AND
- that you clean up table tx_metaseo_sitemap, e.g. by backing up, dropping its contents and then rebuilding it (every page must be http-requested to make it into the cache and metaseo's index!)

As you're still on 6.2.23, which is affected by the DOS attack, I assume that someone successfully DOSed you, unless you really and intentionally have around 1.8 million pages in your page tree.

Please report back if you really have 1.8 million pages or if the clean-up steps fixed the issue.

**Comment by thomaszbz** [comment]
Can't reproduce. Feedback missing.

@ducatisti-bln or other affected users: Please report back if you still think this is an issue.
