### ISSUE TITLE
Incorrect External Links / URLS in Sitemap.xml

### ISSUE THREAD

**Issue by DanPii** [mblaschke/TYPO3-metaseo#306]
Hi there,

I'm using metaSEO 2.0.1 with Typo3 7.6.11.

Right now I've got two Issues:
1.) untranslated pages are not hidden --> see #238 
2.) external links to another website are shown as relative links in sitemap tool leading to incorrect sitemap.xml entry:
Let's say my domain is "https://example.org". All internal Links are correct in sitemap.xml, but when i use page type "Link to external site" and set it to an external site, e.g. "https://url.com/abc", the Sitemap entry is incorrect. The sitemap tool in typo3 BE only shows "abc", the sitemap.xml entry is "https://example.org/abc". So it is mixing up the domains. 
Please see attached pictures.

- Typo3 "Use as Root Page" is properly set.
- domain is added as domain record and correctly shown under "Website-Domain" in SEO Control Center.

I tried:
- clear all caches
- deleting entries in Sitemap Tool in typo3 BE
The entries reappear in the sitemap. Only solution right now is to put all links to the blacklist.

Any ideas how I could fix this?

Thanks,
Daniel

![page_type_external](https://cloud.githubusercontent.com/assets/16837118/21488131/b0397a5c-cb90-11e6-8eae-8975f84252c2.png)

![relative_entry_sitemaptool](https://cloud.githubusercontent.com/assets/16837118/21488132/b04dd6fa-cb90-11e6-8fa7-ec6a7e602252.png)

![incorrect_sitemap_entry](https://cloud.githubusercontent.com/assets/16837118/21488130/b025575c-cb90-11e6-9d27-e2eb6845421a.png)

**MetaSEO version**: 2.0.1

**TYPO3 version**: 7.6.11

**PHP version**: 5.6.29

 CoolURI 1.1.3

**Comment by thomaszbz** [comment]
I assume that this issue is for external URLs _only_ (for untranslated pages, there's #238).

For instance, I can't reproduce the issues with external URLs. As of MetaSEO 2.0.1, external URLs don't make it into MetaSEO's sitemap, whether in the backend nor in the sitemap.xml which gets published. I tested with 6.2.29 and RealURL 2.1.5, however.

Eventually, the issue happens with 7.6 only. Or using CoolURI instead of RealUrl plays a role.

Something you could try is to update to TYPO3 7.6.12 at least. They fixed a lot in terms of caching in 7.6.11 (security fix) and 7.6.12 (mitigating issues from the fix and in general in terms of caching).

Please also make sure that you have applied the security fix via:

    $GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] = true;

To my knowledge, 7.6.11 and 12 fixed a lot of issues in metaseo.

Anyways, metaseo should not index external URLs at all. As soon as this can be reproduced, it's a bug. If you can help us to track it down (expecially _when_ it happens), that would be very helpful.

**Comment by thomaszbz** [comment]
Tried to reproduce this against TYPO3 7.6.14, RealUrl 2.1.5, Metaseo 2.0.2 (current develop branch 5e2273d05573dc01b03459a8b82a249b8abc1b95):

![new typo3 site typo3 cms 7 6 14 - mozilla firefox_097](https://cloud.githubusercontent.com/assets/11200727/21500940/0f345064-cc44-11e6-8342-3ba8a09ac79c.png)

- Cleared all entries from metaseo's sitemap
- Cleared all caches
- Added "link to external URL" (page type)
- Created link on another page to the page with external URL
- logged out from backend
- requested both pages
- found a set of new URLs in the sitemap:

![new typo3 site typo3 cms 7 6 14 - mozilla firefox_098](https://cloud.githubusercontent.com/assets/11200727/21500936/0543b608-cc44-11e6-90c7-ae5d94b76543.png)

The sitemap's urlset looks as follows:

`
<url>
      <loc>http://172.17.0.2/code/asdfs/e/</loc>
      <lastmod>2016-12-27T13:45:21+00:00</lastmod>
      <priority>0.50</priority>
   </url>
   <url>
      <loc>http://172.17.0.2/code/asdfs/f/</loc>
      <lastmod>2016-12-27T13:45:21+00:00</lastmod>
      <priority>0.50</priority>
   </url>
   <url>
      <loc>http://172.17.0.2/code/asdfs/g/</loc>
      <lastmod>2016-12-27T13:45:21+00:00</lastmod>
      <priority>0.50</priority>
   </url>`

**Comment by thomaszbz** [comment]
@DanPii What's your setup in respect to 

    config.absRefPrefix

and 

    config.baseURL

?

**Comment by thomaszbz** [comment]
Workaround: "Exclude page from sitemap" via page properties (tab SEO):

![auswahl_102](https://cloud.githubusercontent.com/assets/11200727/21501531/fd8226fc-cc48-11e6-9cc6-f2f27af9d449.png)

Page `g` still gets indexed, but now it gets blacklisted _automatically_:

![auswahl_103](https://cloud.githubusercontent.com/assets/11200727/21501563/2dd5372c-cc49-11e6-9864-a84fa1f30518.png)

Being blacklisted, page `g` does not appear in the sitemap xml any more:

```
   <url>
      <loc>http://172.17.0.2/code/asdfs/e/</loc>
      <lastmod>2016-12-27T14:24:17+00:00</lastmod>
      <priority>0.50</priority>
   </url>
   <url>
      <loc>http://172.17.0.2/code/asdfs/f/</loc>
      <lastmod>2016-12-27T14:24:17+00:00</lastmod>
      <priority>0.50</priority>
   </url>
```

**Comment by thomaszbz** [comment]
115b385 makes that doktype 3 (external link) is blacklisted for indexation. With the patch applied, pages with doktype 3 are excluded from indexing and don't make it into metaseo's sitemap.

@DanPii would you like to give it a try for your case? You could just manually add the new line to test it.

https://github.com/thomaszbz/TYPO3-metaseo/commit/115b38578b200554b24879c1cb16878d4bf508ce#diff-65bfae4cbd24d7559eddcf39a0824eccR59

**Comment by DanPii** [comment]
Hi Thomas, 

thanks for the quick response. I'm still on the road right now, so here some short feedback.

- I  have set $GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] = true;
- config.absRefPrefix is non existent yet - should I set it to "/"?
- config.baseURL (to stay consistent with my example at the top):  https://example.org - without slash at the end

When I'm back, I will try your recommendations. Update Typo3 to 7.6.12 and then apply your fix.
Maybe it is a bug / problem with CoolURI, but hopefully it can be fixed that way. I'll give you feedback as soon as I've tried -  might take another week or two.

Thanks

**Comment by thomaszbz** [comment]
@DanPii Thanks for reporting back. After merging the fix, I just wanted to have your settings attached to this issue, because sometimes users have similar issues and we need to sort out which one is which.

At first, I wanted to have the infos to track down this issue. But after I could reproduce it, I fixed it no matter if a path prefix is set / which path prefix is set. Would still be great if you could check how it worked out in your installation (note that old entries are not deleted by the fix, you need to do that manually _once_). Similar to your previous test, the entries should not come back this time.

**Comment by DanPii** [comment]
@thomaszbz 

- I  updated Typo3 to 7.6.15 and the metaseo to 2.0.3. 
- Cleared all caches
- deleted all entries of the existing sitemap 

It is still updating the sitemap (about 450 of 600 entries), but none of the external links are included anymore!! This is SOLVED for me.
The other issue (untranslated pages showing up in the sitemap #238) is now solved as well.

Thank you very much for the quick replies and the immediate fix in your plugin. Very appreciated!
