### ISSUE TITLE
8LTS: SEO/Metatags: URL view throws http status 500

### ISSUE THREAD

**Issue by mediaessenz** [mblaschke/TYPO3-metaseo#411]
> "An exception occurred while executing 'SELECT `uid`, `pid`, `is_siteroot`, `title`, `doktype`, `nav_title`, `mount_pid`, `php_tree_stop`, `t3ver_id`, `t3ver_state`, `hidden`, `starttime`, `endtime`, `fe_group`, `module`, `extendToSubpages`, `nav_hide`, `title`, `url_scheme`, `alias`, `tx_realurl_pathsegment`, `tx_realurl_pathoverride`, `tx_realurl_exclude`, `pid` **FROM** `pages` WHERE (`pid` = ?) AND (deleted=0 AND doktype IN (1,4) AND  1=1) AND ((`pages`.`deleted` = 0) AND ((`pages`.`t3ver_wsid` = 0) OR (`pages`.`t3ver_state` <= 0))) ORDER BY `sorting` ASC' with params [1]:↵↵**Unknown column 'url_scheme' in 'field list'"**

Reason: column `url_scheme` does not exists under TYPO3 8.7.0

**Comment by thomaszbz** [comment]
Attribute `pages.url_scheme` was removed in 8 LTS.

https://forge.typo3.org/issues/79302

**Comment by thomaszbz** [comment]
Website owners could still configure schema selection via 301-redirects, configured via web server (e.g. `.htaccess` file).

As soon as both schemas are used for a single domain, Metaseo should know a schema for each page, because otherwise we can't create site maps which contain absolute URLs, correct schema included.

Just by serving both protocols (best effort approach), the size of a sitemap would duplicate . Plus, would search engines either potentially see duplicate content (in case the request is not 301-redirected by a web server) or they would see 301-redirects for half of the pages served by a site map. That said, this is not an option we should go for. Nobody wants to see that in a google search console.

Leaving out the protocol  or serving `//:` instead of `http//:`/`https//:` has pretty much the same disadvantages.

Instead, I **suggest** to
* let MetaSEO have its own database field to set a schema for each page. We can use existing infrastructure for that purpose (e.g. URL view in SEO/Metatags section). Users can edit the field thereafter. It could also be shown in the page properties.
* if nothing is set, we fall back to a typoscript setting which we already [have](https://github.com/mblaschke/TYPO3-metaseo/blob/develop/Configuration/TypoScript/setup.txt#L120) for the canonical URL. To be discussed: If we want to reuse that variable, rename it, or add a separate one for the indexing (canonical URL and indexed page URL might be different, same holds true for their schema!). I'd rather go for the latter: Add a separate config variable for the schema used for indexing.
* if still nothing is set, we can only guess that it's `http://`.

Plan B would be: Always use the protocol which we get via fallbackProtocol configuration variable via Typoscript, leaving out the first bullet. To get a behaviour on a per page basis, users would have to be able to edit their template. Even if they _can_ do that, I think it's not what they _will_ do (leave alone _want_ to do).

In any case, Metaseo should _not_ replace the existing feature. 301-redirecting is something web servers should do, at least in terms of protocol selection (e.g. https-only strategy). As said, Metaseo just needs to know a protocol to generate links in sitemaps. For keeping the feature, there's an extension called `compatibility7`. Btw, should we support the old behaviour via `compatibility7` for some time (only **if** `compatibility7` is installed)? In any case should metaseo be able to operate without the `compatibility7` extension.

**Comment by thomaszbz** [comment]
9d3d0d1 does:

- behave as before in case compatibility7 extension is installed
- if not: Don't render the url_scheme column in the grid and
  don't use the attribute for canonicals.
