### ISSUE TITLE
Cache PageTitle

### ISSUE THREAD

**Issue by mblaschke** [mblaschke/TYPO3-metaseo#7]
If PageTitle is set in extension (pibase or extbase) and there is another USER_INT/COA_INT object in TypoScript, the PageTitle is not set in cached version.

Solution: Make PageTitle cacheable

**Comment by jozefspisiak** [comment]
Hi.

I think we have tracked this one down quite recently in our company, when we were debugging news cached page titles. If you want, I can ask guys to provide some patch for this.

Jozef

**Comment by mblaschke** [comment]
Yes please :)

**Comment by atnexxt** [comment]
Are there any news on this topic?
BR Thomas

**Comment by mblaschke** [comment]
It's still on my todo list

**Comment by mblaschke** [comment]
I will check if i can fix this for 2.0 .. maybe it will be fixed for 2.1

**Comment by mblaschke** [comment]
Implemented with 2.0, anyone who can confirm that this solution is working?!

**Comment by thomaszbz** [comment]
@atnexxt @jozefspisiak @mblaschke  I could test the patch if I some provides the exact steps to reproduce the problem. We should also know if everybody is happy and if we can close this issue.

@mblaschke Please don't remove tags unless there is a reason. If it's a bug, then it was still a bug when the issue is closed. We get a nice list of closed issues in the milestones and still know how we resolved the issue => better overview.

I introduced a tag "patch available" for this. And we should always close issues when we merge. Better use the concept of branches and PR's for tests before a patch is verified.

**Comment by thomaszbz** [comment]
00f8edb now made it into the released 2.0.0 version of metaseo.

As long as everybody is happy, I'm closing this issue now.
